version: '3.9'

services:
  server:
    container_name: server
    restart: always
    tty: true

  database:
    container_name: database
    restart: always
    tty: true

  ml:
    container_name: ml
    restart: always
    tty: true
