version: '3'
services:
  server:
    build:
      context: ../api/Api
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CLIENT_URL=${CLIENT_URL}