version: '3'
services:
  server:
    build:
      context: ../api/Api
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CLIENT_URL=${CLIENT_URL}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
      - GCS_URL=${GCS_URL}
      - ML_URL=${ML_URL}
